### ISSUE TITLE
wrong number for external field in nmag code

### ISSUE THREAD

**Issue by borisgross** [fangohr/micromagnetic-standard-problem-ferromagnetic-resonance#1]
The namg simulation script "02_dynamic_stage.py" in the folder "micromagnetic-standard-problem-ferromagnetic-resonance/src/micromagnetic_simulation_scripts/nmag/" has an error in line 16. 
It is written: H_direction = np.array([1.0, 0.715, 0.0])
But it should be: H_direction = np.array([1.0, 0.7, 0.0])

I am not very familiar with git, so I hope this is the right way to inform you.
Best regards,
Boris

**Comment by fangohr** [comment]
Thank you - that's much appreciated. This is fixed in https://github.com/fangohr/micromagnetic-standard-problem-ferromagnetic-resonance/commit/c7051885417864508bfe6bb3511adad361395b87
